# Generated by Django 2.1 on 2022-04-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
