# Generated by Django 2.1 on 2022-04-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220424_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='category',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
